### ISSUE TITLE
[QUESTION]: MeSH json file

### ISSUE THREAD

**Issue by sg-wbi** [bioinformatics-ua/biocreativeVII_track2#7]
Hi,
could you please tell me how the file `fullMeSH2021.json` is generated?
Thank you in advance!

**Comment by T-Almeida** [comment]
Hi @sg-wbi, my apologies for the late reply, but I did not receive any notification.

I believe that the script that you are looking for was not moved to the main branch, since we decided to make the already preprocessed file available. However, you can find the script in the `joaofsilva-dev` branch under the name [MeSHfiltering.py](https://github.com/bioinformatics-ua/biocreativeVII_track2/blob/joaofsilva-dev/src/MeSHfiltering.py). 

The script is well-documented and should be easy use. I believe that you need to download the MeSH and/or SCR files from the NLM that are in XML format. The script will then convert to JSON format and select the mandatory fields for each entry. It also has an optional filtering feature.

Hey, @manels7 do you have anything to add or correct? or Do you still have or remember the exact command that was executed to generate the `fullMeSH2021.json` file?

@sg-wbi tell me if this answer suffices or if you need anything more specific.

**Comment by manels7** [comment]
Hey. That is correct.

The MeSH XML file provided by NLM must be firstly downloaded and then supplied to the MeSHfiltering script. 

As you said, the script itself is self-explanatory, but to provide some additional info, the user can select whether to extract codes from MeSH or SCR, and which code groups (first level of the MeSH tree number) should be retrieved from these categories.

**Comment by sg-wbi** [comment]
Thank you guys for the detailed  answer! Maybe it is worth to add it to somewhere in the README.md?
The script is very useful and someone might want to update to later MeSH releases.
Thanks again!

**Comment by T-Almeida** [comment]
Hi @sg-wbi, thank you for your feedback. I see your perspective and will add a note in the README. 

I will now close this issue, but please feel free to reopen it if you have any further questions.
